// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_marginal_likelihood
double log_marginal_likelihood(const arma::vec& y0, const arma::vec& yA, const arma::vec& yAb, const arma::mat& X0, const arma::mat& XA, const arma::mat& XAb, const arma::vec& d_A, const arma::vec& d_Ab, const arma::vec& d_delta, const arma::mat& X0_X0_t, const arma::vec& X0_y0, const List& precomp_XtX_A, const List& precomp_Xty_A, const List& precomp_XtX_Ab, const List& precomp_Xty_Ab, bool informative, bool noninformative);
RcppExport SEXP _BLASTreg_log_marginal_likelihood(SEXP y0SEXP, SEXP yASEXP, SEXP yAbSEXP, SEXP X0SEXP, SEXP XASEXP, SEXP XAbSEXP, SEXP d_ASEXP, SEXP d_AbSEXP, SEXP d_deltaSEXP, SEXP X0_X0_tSEXP, SEXP X0_y0SEXP, SEXP precomp_XtX_ASEXP, SEXP precomp_Xty_ASEXP, SEXP precomp_XtX_AbSEXP, SEXP precomp_Xty_AbSEXP, SEXP informativeSEXP, SEXP noninformativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yA(yASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yAb(yAbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XA(XASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XAb(XAbSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_A(d_ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_Ab(d_AbSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_delta(d_deltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0_X0_t(X0_X0_tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X0_y0(X0_y0SEXP);
    Rcpp::traits::input_parameter< const List& >::type precomp_XtX_A(precomp_XtX_ASEXP);
    Rcpp::traits::input_parameter< const List& >::type precomp_Xty_A(precomp_Xty_ASEXP);
    Rcpp::traits::input_parameter< const List& >::type precomp_XtX_Ab(precomp_XtX_AbSEXP);
    Rcpp::traits::input_parameter< const List& >::type precomp_Xty_Ab(precomp_Xty_AbSEXP);
    Rcpp::traits::input_parameter< bool >::type informative(informativeSEXP);
    Rcpp::traits::input_parameter< bool >::type noninformative(noninformativeSEXP);
    rcpp_result_gen = Rcpp::wrap(log_marginal_likelihood(y0, yA, yAb, X0, XA, XAb, d_A, d_Ab, d_delta, X0_X0_t, X0_y0, precomp_XtX_A, precomp_Xty_A, precomp_XtX_Ab, precomp_Xty_Ab, informative, noninformative));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BLASTreg_log_marginal_likelihood", (DL_FUNC) &_BLASTreg_log_marginal_likelihood, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_BLASTreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
