# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_marginal_likelihood <- function(y0, yA, yAb, X0, XA, XAb, d_A, d_Ab, d_delta, X0_X0_t, X0_y0, precomp_XtX_A, precomp_Xty_A, precomp_XtX_Ab, precomp_Xty_Ab, informative, noninformative) {
    .Call(`_BLASTreg_log_marginal_likelihood`, y0, yA, yAb, X0, XA, XAb, d_A, d_Ab, d_delta, X0_X0_t, X0_y0, precomp_XtX_A, precomp_Xty_A, precomp_XtX_Ab, precomp_Xty_Ab, informative, noninformative)
}

